/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gacoan;

import Connections.Koneksi;
import com.barcodelib.barcode.Linear;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Nabiyla Hamestuti
 */
public class barcode extends javax.swing.JFrame {
    public final com.mysql.jdbc.Connection conn = Connections.Koneksi.cekKoneksi();
    
    JasperReport JasRep;
    JasperPrint JasPri;
    Map param = new HashMap();
    JasperDesign JasDes;
    /**
     * Creates new form barcode
     */
    public barcode() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        barcode = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtNama1 = new javax.swing.JTextField();
        btnCetak1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtID1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Background Pemesanan.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barcode.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Garamond", 1, 50)); // NOI18N
        jLabel9.setText("Mie Gacoan Jember");
        barcode.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 460, 50));

        txtNama1.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        barcode.add(txtNama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 300, 30));

        btnCetak1.setBackground(new java.awt.Color(153, 153, 153));
        btnCetak1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        btnCetak1.setText("Cetak Barcode");
        btnCetak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetak1ActionPerformed(evt);
            }
        });
        barcode.add(btnCetak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, -1, -1));

        jLabel10.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel10.setText("Nama pembeli:");
        barcode.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 160, 30));

        jLabel11.setFont(new java.awt.Font("Garamond", 3, 16)); // NOI18N
        jLabel11.setText("Jl. Sumatra No.82, Tegal Boto Lor, Sumbersari, Kec. Sumbersari, Kabupaten Jember, Jawa Timur 68121");
        barcode.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));

        jLabel12.setFont(new java.awt.Font("Garamond", 1, 50)); // NOI18N
        jLabel12.setText("Cetak Barcode Pembayaran");
        barcode.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 600, 50));

        jLabel14.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel14.setText("ID Pemesanan:");
        barcode.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 160, 30));

        txtID1.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        barcode.add(txtID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 300, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ii MIE SETAN2.jpg"))); // NOI18N
        barcode.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 540));

        getContentPane().add(barcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 4, 3530, 1110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCetak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetak1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCetak1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(barcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(barcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(barcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new barcode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barcode;
    private javax.swing.JButton btnCetak1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtID1;
    private javax.swing.JTextField txtNama1;
    // End of variables declaration//GEN-END:variables
}
