/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gacoan;

import Connections.Koneksi;
import com.mysql.jdbc.Connection;
import com.toedter.calendar.JDateChooser;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
//import net.sf.jasperreports.engine.JRException;
//import net.sf.jasperreports.engine.JasperCompileManager;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.engine.JasperReport;
//import net.sf.jasperreports.view.JasperViewer;
import sun.rmi.server.Activation;
import sun.security.pkcs11.Secmod;

/**
 *
 * @author khoirul
 */
public class Menu extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst;
    DefaultTableModel tbmMenu;
    ResultSet rs;
    Statement st;
    
    public Menu() {
        conn = Connections.Koneksi.cekKoneksi();
        initComponents();
        showTable();
        try {
            tampil_combo();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnCari.setEnabled(true);
        btnSimpan.setEnabled(false);
        btnHapus.setEnabled(false);
        btnRubah.setEnabled(false);
        btnBaru.setEnabled(false);
        btnPrint.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RbtnJenis_Kelamin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnPegawai = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnJenis_Menu = new javax.swing.JButton();
        btnPemesanan = new javax.swing.JButton();
        btnPembayaran = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtID_Menu = new javax.swing.JTextField();
        txtMenu = new javax.swing.JTextField();
        txtDetail = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnRubah = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnBaru = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        txtmenu = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbJenis = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnPegawai.setText("Pegawai");
        btnPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegawaiActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");

        btnJenis_Menu.setText("Jenis Menu");

        btnPemesanan.setText("Pemesanan");

        btnPembayaran.setText("Pembayaran");

        btnLaporan.setText("Laporan");

        btnLogOut.setText("LogOut");

        jLabel1.setText("ID Menu *");

        jLabel2.setText("Menu *");

        jLabel4.setText("ID Jenis *");

        jLabel7.setText("Detail *");

        jLabel8.setText("Harga *");

        txtID_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtID_MenuMouseClicked(evt);
            }
        });

        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMenu);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnRubah.setText("Ubah");
        btnRubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRubahActionPerformed(evt);
            }
        });

        btnPrint.setText("Cetak");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnBaru.setText("Baru");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        txtmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtmenuMouseClicked(evt);
            }
        });
        txtmenu.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtmenuInputMethodTextChanged(evt);
            }
        });
        txtmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmenuActionPerformed(evt);
            }
        });

        jLabel11.setText("Masukkan Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMenu)
                            .addComponent(btnPegawai)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnJenis_Menu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPemesanan)
                            .addComponent(btnPembayaran)
                            .addComponent(btnLaporan)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnLogOut)))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(149, 149, 149))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                        .addComponent(txtID_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                        .addComponent(cmbJenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(btnCari))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSimpan)
                            .addComponent(btnHapus)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnBaru)
                                .addComponent(btnRubah)
                                .addComponent(btnPrint))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(488, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnPegawai))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnJenis_Menu)
                        .addGap(79, 79, 79)
                        .addComponent(btnPemesanan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPembayaran)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLaporan)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel11)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCari))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtID_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSimpan))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(cmbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRubah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBaru)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPrint)))))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogOut)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPegawaiActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        String idMenu;
        idMenu = txtID_Menu.getText();
        int opsi = JOptionPane.showConfirmDialog(null, "Apakah anda ingin menghapus data ini ?", "Hapus Data", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        switch (opsi) {
            case JOptionPane.YES_OPTION:
                deleteMenu(idMenu);
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                break;
            case JOptionPane.NO_OPTION:
                JOptionPane.showMessageDialog(null, "Data tidak dihapus");
                break;
        }
        showTable();
        clear();
    }//GEN-LAST:event_btnHapusActionPerformed

    public void tampil_combo() throws SQLException{
        try {
            String query = "SELECT * FROM jenis_menu";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query);
            while (rs.next()){
                cmbJenis.addItem(rs.getString("id_jenis"));
            }
            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();
        } catch (SQLException ex) {
            Logger.getLogger(Koneksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void deleteMenu(String idMenu) {
        try {
            String sql = "DELETE FROM menu WHERE id_menu =?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, idMenu);
            pst.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String id_menu, menu, id_jenis, detail, nilai;
        int harga;
        id_menu = txtID_Menu.getText();
        menu = txtMenu.getText();
        id_jenis = (String) cmbJenis.getSelectedItem();
        nilai = txtHarga.getText();
        detail = txtDetail.getText();
        harga = Integer.parseInt(nilai);
        try {
            if (txtID_Menu.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "ID Menu Tidak Boleh Kosong");
            } else if (txtMenu.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Menu Tidak Boleh Kosong");
            } else if (cmbJenis.getSelectedItem ().equals("")) {
                JOptionPane.showMessageDialog(null, "ID Jenis Tidak Boleh Kosong");
            //} else if (txtJenis.getText().equals("")) {
              //  JOptionPane.showMessageDialog(null, "Jenis Tidak Boleh Kosong");
            } else if (txtDetail.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Detail Tidak Boleh Kosong");
            } else if (txtHarga.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Harga Tidak Boleh Kosong");
            } else {
                int opsi = JOptionPane.showConfirmDialog(null, "Apakah anda ingin menyimpan data ini ?", "Simpan Data", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                switch (opsi) {
                    case JOptionPane.YES_OPTION:
                  insertMenu(id_menu, menu, id_jenis, detail, harga);
                        
                        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                        break;
                    case JOptionPane.NO_OPTION:
                        JOptionPane.showMessageDialog(null, "Data tidak disimpan");
                        break;
                }
            }
        } catch (Exception t) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan!");
        }
        showTable();
        
        clear();
    }//GEN-LAST:event_btnSimpanActionPerformed

    public void insertMenu(String id_menu, String menu, String id_jenis, String detail, int harga) {
        try {
            String sql = "INSERT INTO menu (id_menu, menu, id_jenis, detail, harga) VALUES (?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, id_menu);
            pst.setString(2, menu);
            pst.setString(3, id_jenis);
            pst.setString(4, detail);
            pst.setInt(5, harga);
//            pst.setString(2, menu);
            pst.execute();
        } catch (SQLException ex) {
            System.err.println(ex);
        }
    }

    private void tblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMenuMouseClicked
        // TODO add your handling code here:
        int row = tblMenu.getSelectedRow();
        txtID_Menu.setText(tblMenu.getValueAt(row, 0).toString());
        txtMenu.setText(tblMenu.getValueAt(row, 1).toString());
        cmbJenis.setSelectedItem(tblMenu.getValueAt(row, 2).toString());
//        txtJenis.setText(tblMenu.getValueAt(row, ).toString());
        txtDetail.setText(tblMenu.getValueAt(row, 3).toString());
        txtHarga.setText(tblMenu.getValueAt(row, 4).toString());
        btnRubah.setEnabled(true);
        btnHapus.setEnabled(true);
        btnSimpan.setEnabled(false);
        btnBaru.setEnabled(true);
        btnCari.setEnabled(false);
        showTable();
    }//GEN-LAST:event_tblMenuMouseClicked

    public ResultSet selectMenu() {
        try {
            String sql = "SELECT * FROM menu";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Koneksi.class.getName()).log(Level.SEVERE, null, ex);
        }
        return rs;
    }

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusMouseClicked

    private void btnRubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRubahActionPerformed
        // TODO add your handling code here:
        String id_menu, menu, id_jenis, jenis, detail;
        int harga = 0;
        id_menu = txtID_Menu.getText();
        menu = txtMenu.getText();
        id_jenis = (String) cmbJenis.getSelectedItem();
        //jenis = txtJenis.getText();
        detail = txtDetail.getText();
//        harga = txtHarga.getText();

        try {
            if (txtID_Menu.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "ID Menu Tidak Boleh Kosong");
            } else if (txtMenu.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Menu Tidak Boleh Kosong");
            } else if (cmbJenis.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog(null, "ID Jenis Tidak Boleh Kosong");
            //} else if (txtJenis.getText().equals("")) {
              //  JOptionPane.showMessageDialog(null, "Jenis Tidak Boleh Kosong");
            } else if (txtDetail.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Detail Tidak Boleh Kosong");
            } else if (txtHarga.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Harga Tidak Boleh Kosong");
            } else {
                int opsi = JOptionPane.showConfirmDialog(null, "Apakah anda ingin merubah data ini ?", "Rubah Data", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                switch (opsi) {
                    case JOptionPane.YES_OPTION:
                      updateMenu(id_menu, menu, id_jenis, detail, harga);
                        
                        JOptionPane.showMessageDialog(null, "Data berhasil dirubah");
                        break;
                    case JOptionPane.NO_OPTION:
                        JOptionPane.showMessageDialog(null, "Data tidak dirubah");
                        break;
                }
            }
        } catch (Exception t) {
            JOptionPane.showMessageDialog(null, "Data Gagal Dirubah!");
        }
        showTable();
        clear();
    }//GEN-LAST:event_btnRubahActionPerformed

    public void updateMenu(String id_menu, String menu, String id_jenis, String detail, int harga) {
        try {
            String sql = "UPDATE menu SET menu=?, id_jenis=?, detail=?, detail=?, harga=? WHERE id_menu=?";
            pst = conn.prepareStatement(sql);
            pst.setString(5, id_menu);
            pst.setString(1, menu);
            pst.setString(2, id_jenis);
            pst.setString(3, detail);
            pst.setInt(4, harga);
            pst.executeUpdate();
        } catch (SQLException ex) {
            System.err.println(ex);
        }
    }

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
  //      Connections.Koneksi.print();
    }//GEN-LAST:event_btnPrintActionPerformed

    public void clear() {
        txtID_Menu.setText("");
        txtMenu.setText("");
        cmbJenis.setSelectedItem("");
        //txtJenis.setText("");
        txtDetail.setText("");
        txtHarga.setText("");
        btnRubah.setEnabled(false);
        btnHapus.setEnabled(false);
        btnSimpan.setEnabled(true);
    }
    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnBaruActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String menu = txtmenu.getText();
        try {
            com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement) conn.createStatement();
            ResultSet rs = statement.executeQuery("SELECT * FROM menu where menu='" + menu + "'");
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("ID Menu");
            tbl.addColumn("Menu");
            tbl.addColumn("ID Jenis");
            tbl.addColumn("Detail");
            tbl.addColumn("Harga");
            
            tblMenu.setModel(tbl);

            while (rs.next()) {
                tbl.addRow(new Object[]{
                    rs.getString("id_menu"),
                    rs.getString("menu"),
                    rs.getString("id_jenis"),
                    rs.getString("detail"),
                    rs.getString("harga")});
                tblMenu.setModel(tbl);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data Yang Anda Cari Tidak Sesuai");
        }
        txtmenu.setText("");
    }//GEN-LAST:event_btnCariActionPerformed

    private void txtmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmenuMouseClicked
        // TODO add your handling code here:
        btnCari.setEnabled(true);
        btnSimpan.setEnabled(false);
        clear();
    }//GEN-LAST:event_txtmenuMouseClicked

    private void txtmenuInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtmenuInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmenuInputMethodTextChanged

    private void txtID_MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtID_MenuMouseClicked
        // TODO add your handling code here:
        btnSimpan.setEnabled(true);
        btnBaru.setEnabled(true);
        btnCari.setEnabled(false);
    }//GEN-LAST:event_txtID_MenuMouseClicked

    private void txtmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmenuActionPerformed

    public void showTable() {
        try {
            tbmMenu = new DefaultTableModel(new String[]{"ID Menu", "Menu", "ID Jenis", "Detail", "Harga"}, 0);
            ResultSet rs;
            rs = selectMenu();
            while (rs.next()) {
                tbmMenu.addRow(new Object[]{
                    rs.getString("id_menu"),
                    rs.getString("menu"),
                    rs.getString("id_jenis"),
                    rs.getString("detail"),
                    rs.getString("harga")});
            }
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblMenu.setModel(tbmMenu);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup RbtnJenis_Kelamin;
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnJenis_Menu;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPegawai;
    private javax.swing.JButton btnPembayaran;
    private javax.swing.JButton btnPemesanan;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRubah;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTextField txtDetail;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtID_Menu;
    private javax.swing.JTextField txtMenu;
    private javax.swing.JTextField txtmenu;
    // End of variables declaration//GEN-END:variables
}
