/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gacoan;

import Connections.Koneksi;
import com.mysql.jdbc.Connection;
import com.toedter.calendar.JDateChooser;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.sql.Blob;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
//import net.sf.jasperreports.engine.JRException;
//import net.sf.jasperreports.engine.JasperCompileManager;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.engine.JasperReport;
//import net.sf.jasperreports.view.JasperViewer;
import sun.rmi.server.Activation;
import sun.security.pkcs11.Secmod;

/**
 *
 * @author khoirul
 */
public class Pegawai extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst;
    DefaultTableModel tbmPegawai;
    ResultSet rs;
    Statement st;
    Image image;
    String path;
    byte[] byteArr;
    ImageIcon icon;
    private byte[] foto;

    public byte[] getFoto() {
        return foto;
    }

    public void setFoto(byte[] foto) {
        this.foto = foto;
    }

    public Pegawai() {
        conn = Connections.Koneksi.cekKoneksi();
        initComponents();
        showTable();
        btnCari.setEnabled(true);
        btnSimpan.setEnabled(false);
        btnHapus.setEnabled(false);
        btnRubah.setEnabled(false);
        btnBaru.setEnabled(false);
        btnAttach.setEnabled(false);
//        btnPrint.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RbtnJenis_Kelamin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnPegawai = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnJenis_Menu = new javax.swing.JButton();
        btnPemesanan = new javax.swing.JButton();
        btnPembayaran = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtID_Pegawai = new javax.swing.JTextField();
        txtNama_Pegawai = new javax.swing.JTextField();
        txtTempat_Lahir = new javax.swing.JTextField();
        txtAlamat_Kota = new javax.swing.JTextField();
        txtNo_Telepon = new javax.swing.JTextField();
        txtFoto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPegawai = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnRubah = new javax.swing.JButton();
        btnAttach = new javax.swing.JButton();
        jdcTanggal_Lahir = new com.toedter.calendar.JDateChooser();
        RbtnLaki_Laki = new javax.swing.JRadioButton();
        RbtnPerempuan = new javax.swing.JRadioButton();
        txtPassword = new javax.swing.JPasswordField();
        btnBaru = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        txtnama = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbJabatan = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblFoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        btnPegawai.setText("Pegawai");
        btnPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegawaiActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");

        btnJenis_Menu.setText("Jenis Menu");

        btnPemesanan.setText("Pemesanan");

        btnPembayaran.setText("Pembayaran");

        btnLaporan.setText("Laporan");

        btnLogOut.setText("LogOut");

        jLabel1.setText("ID Pegawai *");

        jLabel2.setText("Nama *");

        jLabel3.setText("Jenis Kelamin");

        jLabel4.setText("Tempat Lahir *");

        jLabel5.setText("Tanggal Lahir");

        jLabel6.setText("Alamat (Kota) *");

        jLabel7.setText("Jabatan *");

        jLabel8.setText("No Telepon *");

        jLabel9.setText("Password");

        jLabel10.setText("Foto");

        txtID_Pegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtID_PegawaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtID_PegawaiMouseEntered(evt);
            }
        });
        txtID_Pegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID_PegawaiActionPerformed(evt);
            }
        });

        txtNama_Pegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNama_PegawaiMouseClicked(evt);
            }
        });

        txtTempat_Lahir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTempat_LahirMouseClicked(evt);
            }
        });

        txtAlamat_Kota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAlamat_KotaMouseClicked(evt);
            }
        });

        txtNo_Telepon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNo_TeleponMouseClicked(evt);
            }
        });

        tblPegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPegawaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPegawai);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnRubah.setText("Rubah");
        btnRubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRubahActionPerformed(evt);
            }
        });

        btnAttach.setText("...");
        btnAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachActionPerformed(evt);
            }
        });

        jdcTanggal_Lahir.setDateFormatString("yyyy-MM-dd\n");
        jdcTanggal_Lahir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdcTanggal_LahirMouseClicked(evt);
            }
        });

        RbtnJenis_Kelamin.add(RbtnLaki_Laki);
        RbtnLaki_Laki.setText("Laki - Laki");

        RbtnJenis_Kelamin.add(RbtnPerempuan);
        RbtnPerempuan.setText("Perempuan");

        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });

        btnBaru.setText("Baru");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        txtnama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnamaMouseClicked(evt);
            }
        });
        txtnama.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtnamaInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        jLabel11.setText("Masukkan Nama");

        cmbJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---SELECT---", "Manager", "Kasir", "Crew" }));
        cmbJabatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbJabatanMouseClicked(evt);
            }
        });

        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(lblFoto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMenu)
                            .addComponent(btnPegawai)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnJenis_Menu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPemesanan)
                            .addComponent(btnPembayaran)
                            .addComponent(btnLaporan)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnLogOut)))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtAlamat_Kota, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel4))
                                    .addGap(114, 114, 114)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTempat_Lahir, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNama_Pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtID_Pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jdcTanggal_Lahir, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(RbtnLaki_Laki)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(RbtnPerempuan))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(btnCari))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNo_Telepon, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                        .addComponent(cmbJabatan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(btnAttach))))
                            .addComponent(btnBaru)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnRubah)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(488, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCari))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtID_Pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAttach)
                            .addComponent(btnPegawai))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNama_Pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtTempat_Lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jdcTanggal_Lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(RbtnLaki_Laki)
                                            .addComponent(RbtnPerempuan))
                                        .addGap(18, 18, 18)
                                        .addComponent(txtAlamat_Kota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNo_Telepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBaru)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnJenis_Menu)
                        .addGap(79, 79, 79)
                        .addComponent(btnPemesanan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnRubah)
                                .addComponent(btnSimpan)
                                .addComponent(btnHapus))
                            .addComponent(btnPembayaran))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLaporan)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogOut)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPegawaiActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        String idPegawai;
        idPegawai = txtID_Pegawai.getText();
        int opsi = JOptionPane.showConfirmDialog(null, "Apakah anda ingin menghapus data ini ?", "Hapus Data", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        switch (opsi) {
            case JOptionPane.YES_OPTION:
                deletePegawai(idPegawai);
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                break;
            case JOptionPane.NO_OPTION:
                JOptionPane.showMessageDialog(null, "Data tidak dihapus");
                break;
        }
        showTable();
        clear();
    }//GEN-LAST:event_btnHapusActionPerformed

    public void deletePegawai(String idPegawai) {
        try {
            String sql = "DELETE FROM pegawai WHERE id_pegawai =?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, idPegawai);
            pst.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Pegawai.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String id_pegawai, nama_pegawai, jenis_kelamin, tempat_lahir, alamat_kota, password, jabatan, no_telepon;
        Date tanggal_lahir = null;
        try {
            id_pegawai = txtID_Pegawai.getText();
            nama_pegawai = txtNama_Pegawai.getText();
            jenis_kelamin = RbtnJenis_Kelamin.getSelection().getActionCommand();
            RbtnLaki_Laki.setActionCommand("Laki - Laki");
            RbtnPerempuan.setActionCommand("Perempuan");
            if (RbtnLaki_Laki.isSelected()) {
                jenis_kelamin = "Laki - Laki";
            } else if (RbtnPerempuan.isSelected()) {
                jenis_kelamin = "Perempuan";
            }
            tempat_lahir = txtTempat_Lahir.getText();
            alamat_kota = txtAlamat_Kota.getText();
            password = txtPassword.getText();
            jabatan = (String) cmbJabatan.getSelectedItem();
            no_telepon = txtNo_Telepon.getText();
            if (!txtFoto.getText().equals("")) {
                ObjectOutputStream objectOutputStream = null;
                ByteArrayOutputStream output = new ByteArrayOutputStream();
                File img = new File(path);
                FileInputStream input = new FileInputStream(img);
                try {
                    byte[] buf = new byte[1024];
                    for (int readbyte; (readbyte = input.read(buf)) != -1;) {
                        output.write(buf, 0, readbyte);
                    }
                    byteArr = output.toByteArray();
                    setFoto(byteArr);
                } catch (IOException ex) {
                    Logger.getLogger(Pegawai.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            try {
                if (txtID_Pegawai.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "ID Tidak Boleh Kosong");
                } else if (txtNama_Pegawai.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Nama Tidak Boleh Kosong");
                } else if (txtTempat_Lahir.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Tempat Lahir Tidak Boleh Kosong");
                } //            else if (jdcTanggal_Lahir.getDate().equals("")) {
                //                JOptionPane.showMessageDialog(null, "Tanggal Lahir Tidak Boleh Kosong");
                //            } 
                else if (txtAlamat_Kota.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Alamat Tidak Boleh Kosong");
                } else if (cmbJabatan.getSelectedItem().equals("")) {
                    JOptionPane.showMessageDialog(null, "Jabatan Tidak Boleh Kosong");
                } else if (txtNo_Telepon.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "No Telepon Tidak Boleh Kosong");
                } else if (txtPassword.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Password Tidak Boleh Kosong");
                } else {
                    int opsi = JOptionPane.showConfirmDialog(null, "Apakah anda ingin menyimpan data ini ?", "Simpan Data", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                    switch (opsi) {
                        case JOptionPane.YES_OPTION:
                            insertPegawai(id_pegawai, nama_pegawai, jenis_kelamin, tempat_lahir, tanggal_lahir, alamat_kota, password, jabatan, no_telepon, foto);
                            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                            clear();
                            break;
                        case JOptionPane.NO_OPTION:
                            JOptionPane.showMessageDialog(null, "Data tidak disimpan");
                            break;
                    }
                }
            } catch (Exception t) {
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan!");
            }
        } catch (Exception e) {
        }
        showTable();
    }//GEN-LAST:event_btnSimpanActionPerformed

    public void insertPegawai(String id_pegawai, String nama_pegawai, String jenis_kelamin, String tempat_lahir, Date tanggal_lahir, String alamat_kota, String password, String jabatan, String no_telepon, byte[] foto) {
        try {
            String sql = "INSERT INTO pegawai (id_pegawai, nama_pegawai, jenis_kelamin, tempat_lahir, tanggal_lahir, alamat_kota, password, jabatan, no_telepon, foto) VALUES (?,?,?,?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, id_pegawai);
            pst.setString(2, nama_pegawai);
            pst.setString(3, jenis_kelamin);
            pst.setString(4, tempat_lahir);
            pst.setString(5, ((JTextField) jdcTanggal_Lahir.getDateEditor().getUiComponent()).getText());
            pst.setString(6, alamat_kota);
            pst.setString(7, password);
            pst.setString(8, jabatan);
            pst.setString(9, no_telepon);
            pst.setBytes(10, foto);
            pst.execute();
        } catch (SQLException ex) {
            System.err.println(ex);
        }
    }

    private void tblPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPegawaiMouseClicked
        // TODO add your handling code here:
        int row = tblPegawai.getSelectedRow();
        String jenis_kelamin = tbmPegawai.getValueAt(row, 2).toString();
        txtID_Pegawai.setText(tblPegawai.getValueAt(row, 0).toString());
        txtNama_Pegawai.setText(tblPegawai.getValueAt(row, 1).toString());
        if (jenis_kelamin.equals(RbtnLaki_Laki.getActionCommand())) {
            RbtnLaki_Laki.setSelected(true);
        }
        if (jenis_kelamin.equals(RbtnPerempuan.getActionCommand())) {
            RbtnPerempuan.setSelected(true);
        } else {
            RbtnLaki_Laki.setSelected(false);
            RbtnPerempuan.setSelected(false);
        }
        txtTempat_Lahir.setText(tblPegawai.getValueAt(row, 3).toString());
        jdcTanggal_Lahir.setDate(Date.valueOf(tblPegawai.getValueAt(row, 4).toString()));
        txtAlamat_Kota.setText(tblPegawai.getValueAt(row, 5).toString());
        txtPassword.setText(tblPegawai.getValueAt(row, 6).toString());
        cmbJabatan.setSelectedItem(tblPegawai.getValueAt(row, 7).toString());
        txtNo_Telepon.setText(tblPegawai.getValueAt(row, 8).toString());
        btnRubah.setEnabled(true);
        btnHapus.setEnabled(true);
        btnSimpan.setEnabled(false);
        btnAttach.setEnabled(true);
        btnBaru.setEnabled(true);
        btnCari.setEnabled(false);

        try {
            st = conn.createStatement();
            String sql = "SELECT * FROM pegawai where nama_pegawai='" + txtNama_Pegawai.getText() + "';";
            rs = st.executeQuery(sql);
            while (rs.next()) {
                Blob Gambar = rs.getBlob("foto");
                int ukuran = (int) Gambar.length();
                icon = new ImageIcon(Gambar.getBytes(1, ukuran));
                lblFoto.setIcon(icon);
            }
        } catch (SQLException e) {
            System.out.println("Gambar tidak tampil " + e);
        }
        showTable();
        lblFoto.setVisible(true);
    }//GEN-LAST:event_tblPegawaiMouseClicked

    public ResultSet selectPegawai() {
        try {
            String sql = "SELECT * FROM pegawai";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Koneksi.class.getName()).log(Level.SEVERE, null, ex);
        }
        return rs;
    }

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusMouseClicked

    private void btnRubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRubahActionPerformed
        // TODO add your handling code here:
        String id_pegawai, nama_pegawai, jenis_kelamin, tempat_lahir, alamat_kota, password, jabatan, no_telepon;
        Date tanggal_lahir = null;
        try {
            id_pegawai = txtID_Pegawai.getText();
            nama_pegawai = txtNama_Pegawai.getText();
            jenis_kelamin = RbtnJenis_Kelamin.getSelection().getActionCommand();
            RbtnLaki_Laki.setActionCommand("Laki - Laki");
            RbtnPerempuan.setActionCommand("Perempuan");
            if (RbtnLaki_Laki.isSelected()) {
                jenis_kelamin = "Laki - Laki";
            } else if (RbtnPerempuan.isSelected()) {
                jenis_kelamin = "Perempuan";
            }
            tempat_lahir = txtTempat_Lahir.getText();
            alamat_kota = txtAlamat_Kota.getText();
            password = txtPassword.getText();
            jabatan = (String) cmbJabatan.getSelectedItem();
            no_telepon = txtNo_Telepon.getText();
            if (!txtFoto.getText().equals("")) {
                ObjectOutputStream objectOutputStream = null;
                ByteArrayOutputStream output = new ByteArrayOutputStream();
                File img = new File(path);
                FileInputStream input = new FileInputStream(img);
                try {
                    byte[] buf = new byte[1024];
                    for (int readbyte; (readbyte = input.read(buf)) != -1;) {
                        output.write(buf, 0, readbyte);
                    }
                    byteArr = output.toByteArray();
                    setFoto(byteArr);
                } catch (IOException ex) {
                    Logger.getLogger(Pegawai.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            try {
                if (txtID_Pegawai.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "ID Tidak Boleh Kosong");
                } else if (txtNama_Pegawai.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Nama Tidak Boleh Kosong");
                } else if (txtTempat_Lahir.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Tempat Lahir Tidak Boleh Kosong");
                } //            else if (jdcTanggal_Lahir.getDate().equals("")) {
                //                JOptionPane.showMessageDialog(null, "Tanggal Lahir Tidak Boleh Kosong");
                //            } 
                else if (txtAlamat_Kota.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Alamat Tidak Boleh Kosong");
                } else if (cmbJabatan.getSelectedItem().equals("")) {
                    JOptionPane.showMessageDialog(null, "Jabatan Tidak Boleh Kosong");
                } else if (txtNo_Telepon.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "No Telepon Tidak Boleh Kosong");
                } else if (txtPassword.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Password Tidak Boleh Kosong");
                } else {
                    int opsi = JOptionPane.showConfirmDialog(null, "Apakah anda ingin merubah data ini ?", "Rubah Data", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                    switch (opsi) {
                        case JOptionPane.YES_OPTION:
                            updatePegawai(id_pegawai, nama_pegawai, jenis_kelamin, tempat_lahir, tanggal_lahir, alamat_kota, password, jabatan, no_telepon, foto);
                            JOptionPane.showMessageDialog(null, "Data berhasil dirubah");
                            clear();
                            break;
                        case JOptionPane.NO_OPTION:
                            JOptionPane.showMessageDialog(null, "Data tidak dirubah");
                            break;
                    }
                }
            } catch (Exception t) {
                JOptionPane.showMessageDialog(null, "Data Gagal Dirubah!");
            }
        } catch (Exception e) {
        }
        showTable();
    }//GEN-LAST:event_btnRubahActionPerformed

    public void updatePegawai(String id_pegawai, String nama_pegawai, String jenis_kelamin, String tempat_lahir, Date tanggal_lahir, String alamat_kota, String password, String jabatan, String no_telepon, byte[] foto) {
        try {
            String sql = "UPDATE pegawai SET nama_pegawai=?, jenis_kelamin=?, tempat_lahir=?, tanggal_lahir=?, alamat_kota=?, password=?, jabatan=?, no_telepon=?, foto=? WHERE id_pegawai=?";
            pst = conn.prepareStatement(sql);
            pst.setString(10, id_pegawai);
            pst.setString(1, nama_pegawai);
            pst.setString(2, jenis_kelamin);
            pst.setString(3, tempat_lahir);
            pst.setString(4, ((JTextField) jdcTanggal_Lahir.getDateEditor().getUiComponent()).getText());
            pst.setString(5, alamat_kota);
            pst.setString(6, password);
            pst.setString(7, jabatan);
            pst.setString(8, no_telepon);
            pst.setBytes(9, foto);
            pst.executeUpdate();
        } catch (SQLException ex) {
            System.err.println(ex);
        }
    }

    private void btnAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser(System.getProperty("user.home"));
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setFileFilter(new FileNameExtensionFilter("jpg|png|bmp", "jpg", "png", "bmp"));
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            try {
                if (file.length() > 67108864) {
                    JOptionPane.showMessageDialog(rootPane, "Gambar terlalu besar", "Max 64mb", JOptionPane.WARNING_MESSAGE);
                } else {
                    image = ImageIO.read(file);
                    icon = new ImageIcon(image);
                    lblFoto.setIcon(icon);
                    path = file.getAbsolutePath();
                    lblFoto.setVisible(true);
                }
            } catch (IOException ex) {
                System.out.println("Gambar tidak berhasil dimuat " + ex);
            }
            txtFoto.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_btnAttachActionPerformed

    public void clear() {
        txtID_Pegawai.setText("");
        txtNama_Pegawai.setText("");
        RbtnJenis_Kelamin.clearSelection();
        txtTempat_Lahir.setText("");
        jdcTanggal_Lahir.setCalendar(null);
        txtAlamat_Kota.setText("");
        cmbJabatan.setSelectedItem("");
        txtNo_Telepon.setText("");
        txtPassword.setText("");
        txtFoto.setText("");
        lblFoto.setVisible(false);
        btnRubah.setEnabled(false);
        btnHapus.setEnabled(false);
        btnSimpan.setEnabled(true);
    }
    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnBaruActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String nama_pegawai = txtnama.getText();
        try {
            com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement) conn.createStatement();
            ResultSet rs = statement.executeQuery("SELECT * FROM pegawai where nama_pegawai='" + nama_pegawai + "'");
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("ID Pembeli");
            tbl.addColumn("Nama Pembeli");
            tbl.addColumn("Jenis Kelamin");
            tbl.addColumn("Tanggal Lahir");
            tbl.addColumn("Tempat Lahir");
            tbl.addColumn("Alamat (Kota)");
            tbl.addColumn("Jabatan");
            tbl.addColumn("No Telepon");
            tbl.addColumn("Password");
            tbl.addColumn("Foto");

            tblPegawai.setModel(tbl);

            while (rs.next()) {
                tbl.addRow(new Object[]{
                    rs.getString("id_pegawai"),
                    rs.getString("nama_pegawai"),
                    rs.getString("jenis_kelamin"),
                    rs.getString("tempat_lahir"),
                    rs.getString("tanggal_lahir"),
                    rs.getString("alamat_kota"),
                    rs.getString("password"),
                    rs.getString("jabatan"),
                    rs.getString("no_telepon"),
                    rs.getByte("foto")});
                tblPegawai.setModel(tbl);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data Yang Anda Cari Tidak Sesuai");
        }
        txtnama.setText("");

    }//GEN-LAST:event_btnCariActionPerformed

    private void txtnamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnamaMouseClicked
        // TODO add your handling code here:
        btnCari.setEnabled(true);
        btnSimpan.setEnabled(false);
        clear();
    }//GEN-LAST:event_txtnamaMouseClicked

    private void txtnamaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtnamaInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaInputMethodTextChanged

    private void txtID_PegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtID_PegawaiMouseClicked
        // TODO add your handling code here:
        btnSimpan.setEnabled(true);
        btnBaru.setEnabled(true);
        btnAttach.setEnabled(true);
        btnCari.setEnabled(false);
    }//GEN-LAST:event_txtID_PegawaiMouseClicked

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        lblFoto.setVisible(false);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void txtID_PegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID_PegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID_PegawaiActionPerformed

    private void txtNama_PegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNama_PegawaiMouseClicked
        // TODO add your handling code here:
        btnSimpan.setEnabled(true);
        btnBaru.setEnabled(true);
        btnAttach.setEnabled(true);
        btnCari.setEnabled(false);
    }//GEN-LAST:event_txtNama_PegawaiMouseClicked

    private void txtTempat_LahirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTempat_LahirMouseClicked
        // TODO add your handling code here:
        btnSimpan.setEnabled(true);
        btnBaru.setEnabled(true);
        btnAttach.setEnabled(true);
        btnCari.setEnabled(false);
    }//GEN-LAST:event_txtTempat_LahirMouseClicked

    private void jdcTanggal_LahirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdcTanggal_LahirMouseClicked
        // TODO add your handling code here:
        btnSimpan.setEnabled(true);
        btnBaru.setEnabled(true);
        btnAttach.setEnabled(true);
        btnCari.setEnabled(false);
    }//GEN-LAST:event_jdcTanggal_LahirMouseClicked

    private void txtAlamat_KotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAlamat_KotaMouseClicked
        // TODO add your handling code here:
        btnSimpan.setEnabled(true);
        btnBaru.setEnabled(true);
        btnAttach.setEnabled(true);
        btnCari.setEnabled(false);
    }//GEN-LAST:event_txtAlamat_KotaMouseClicked

    private void cmbJabatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbJabatanMouseClicked
        // TODO add your handling code here:
        btnSimpan.setEnabled(true);
        btnBaru.setEnabled(true);
        btnAttach.setEnabled(true);
        btnCari.setEnabled(false);
    }//GEN-LAST:event_cmbJabatanMouseClicked

    private void txtNo_TeleponMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNo_TeleponMouseClicked
        // TODO add your handling code here:
        btnSimpan.setEnabled(true);
        btnBaru.setEnabled(true);
        btnAttach.setEnabled(true);
        btnCari.setEnabled(false);
    }//GEN-LAST:event_txtNo_TeleponMouseClicked

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        // TODO add your handling code here:
        btnSimpan.setEnabled(true);
        btnBaru.setEnabled(true);
        btnAttach.setEnabled(true);
        btnCari.setEnabled(false);
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void txtID_PegawaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtID_PegawaiMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID_PegawaiMouseEntered

    public void showTable() {
        try {
            tbmPegawai = new DefaultTableModel(new String[]{"ID Pegawai", "Nama Pegawai", "Jenis Kelamin", "Tempat Lahir", "Tanggal Lahir", "Alamat (Kota)", "Jabatan", "No Telepon", "Password", "Foto"}, 0);
            ResultSet rs;
            rs = selectPegawai();
            while (rs.next()) {
                tbmPegawai.addRow(new Object[]{
                    rs.getString("id_pegawai"),
                    rs.getString("nama_pegawai"),
                    rs.getString("jenis_kelamin"),
                    rs.getString("tempat_lahir"),
                    rs.getString("tanggal_lahir"),
                    rs.getString("alamat_kota"),
                    rs.getString("password"),
                    rs.getString("jabatan"),
                    rs.getString("no_telepon"),
                    rs.getBlob("foto")});
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pegawai.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblPegawai.setModel(tbmPegawai);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup RbtnJenis_Kelamin;
    private javax.swing.JRadioButton RbtnLaki_Laki;
    private javax.swing.JRadioButton RbtnPerempuan;
    private javax.swing.JButton btnAttach;
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnJenis_Menu;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPegawai;
    private javax.swing.JButton btnPembayaran;
    private javax.swing.JButton btnPemesanan;
    private javax.swing.JButton btnRubah;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbJabatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdcTanggal_Lahir;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JTable tblPegawai;
    private javax.swing.JTextField txtAlamat_Kota;
    private javax.swing.JTextField txtFoto;
    private javax.swing.JTextField txtID_Pegawai;
    private javax.swing.JTextField txtNama_Pegawai;
    private javax.swing.JTextField txtNo_Telepon;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTempat_Lahir;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables
}
