/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gacoan;

import Connections.Koneksi;
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khoirul
 */
public class Pembayaran extends javax.swing.JFrame {

    /**
     * Creates new form Pesanan
     */
    Connection conn;
    PreparedStatement pst;
    PreparedStatement pst1;
    DefaultTableModel tbmPemesanan = new DefaultTableModel();
    ResultSet rs;
    Statement st;
    Date tanggal_pemesanan;

    public Pembayaran() {
        conn = Connections.Koneksi.cekKoneksi();
        initComponents();
        try {
            tampil_comboPegawai();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        autoNumber(txtID_Pembayaran);
//        auto_numberDetailPemesanan();
//        auto_numberPemesanan();
        jdcTanggal_Pembayaran.setDate(new Date());
//        String nama_pembeli = JOptionPane.showInputDialog(null, "Siapa nama anda?", "Masukkan nama anda!", JOptionPane.PLAIN_MESSAGE);
//        JOptionPane.showMessageDialog(null, "Halo " + nama_pembeli + ":)", "Selamat Datang di Mie Gacoan Jember", JOptionPane.PLAIN_MESSAGE);
//        txtNama_Pembeli.setText(nama_pembeli);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Noodle = new javax.swing.JPanel();
        info = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Input = new javax.swing.JPanel();
        t1 = new javax.swing.JLabel();
        txtID_Pemesanan = new javax.swing.JTextField();
        t6 = new javax.swing.JLabel();
        t7 = new javax.swing.JLabel();
        t8 = new javax.swing.JLabel();
        t9 = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();
        txtBayar = new javax.swing.JTextField();
        txtTotal_Bayar = new javax.swing.JTextField();
        txtNama_Pembeli = new javax.swing.JTextField();
        jdcTanggal_Pembayaran = new com.toedter.calendar.JDateChooser();
        t13 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        t28 = new javax.swing.JLabel();
        txtID_Pegawai = new javax.swing.JTextField();
        txtID_Pembayaran = new javax.swing.JTextField();
        t29 = new javax.swing.JLabel();
        cmbPegawai = new javax.swing.JComboBox<>();
        t30 = new javax.swing.JLabel();
        t10 = new javax.swing.JLabel();
        jdcTanggal_Pemesanan = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Noodle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        info.setBackground(new java.awt.Color(255, 255, 255,0));
        info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Garamond", 1, 20)); // NOI18N
        jLabel5.setText("PEMBAYARAN !!!");
        info.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Garamond", 1, 20)); // NOI18N
        jLabel6.setText("Halaman ini hanya ");
        info.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Garamond", 1, 20)); // NOI18N
        jLabel7.setText("untuk admin atau pegawai dari");
        info.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Garamond", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 255));
        jLabel8.setText("Mie");
        info.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Garamond", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 153, 255));
        jLabel9.setText("Gacoan");
        info.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Garamond", 1, 20)); // NOI18N
        jLabel10.setText("Terimakasih. :)");
        info.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        Noodle.add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 320, 340));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoGacoanAdmin_Resize.png"))); // NOI18N
        Noodle.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Noodle.PNG"))); // NOI18N
        Noodle.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 700));

        Background.add(Noodle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 470, 700));

        Input.setBackground(new java.awt.Color(0, 204, 204));
        Input.setForeground(new java.awt.Color(153, 255, 255));
        Input.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t1.setText("ID Pemesanan");
        Input.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        txtID_Pemesanan.setBackground(new java.awt.Color(0, 255, 255));
        txtID_Pemesanan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtID_Pemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID_PemesananActionPerformed(evt);
            }
        });
        Input.add(txtID_Pemesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 400, 30));

        t6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t6.setText("Waktu");
        Input.add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        t7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t7.setText("Total Bayar");
        Input.add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        t8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t8.setText("Bayar");
        Input.add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        t9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t9.setText("Kembalian");
        Input.add(t9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, -1));

        txtKembalian.setBackground(new java.awt.Color(204, 204, 255));
        txtKembalian.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        txtKembalian.setForeground(new java.awt.Color(255, 0, 51));
        Input.add(txtKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 400, 70));

        txtBayar.setBackground(new java.awt.Color(0, 255, 255));
        txtBayar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBayarActionPerformed(evt);
            }
        });
        Input.add(txtBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 400, 30));

        txtTotal_Bayar.setBackground(new java.awt.Color(204, 204, 255));
        txtTotal_Bayar.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        txtTotal_Bayar.setForeground(new java.awt.Color(255, 0, 51));
        Input.add(txtTotal_Bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 400, 70));

        txtNama_Pembeli.setBackground(new java.awt.Color(0, 255, 255));
        txtNama_Pembeli.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Input.add(txtNama_Pembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 400, 30));

        jdcTanggal_Pembayaran.setBackground(new java.awt.Color(0, 255, 255));
        jdcTanggal_Pembayaran.setDateFormatString("yyyy-MM-dd");
        Input.add(jdcTanggal_Pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 400, 30));

        t13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t13.setText("Nama Pembeli");
        Input.add(t13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        btnSimpan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        Input.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 600, 170, 60));

        t28.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t28.setText("Nama Pegawai");
        Input.add(t28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        txtID_Pegawai.setBackground(new java.awt.Color(0, 255, 255));
        txtID_Pegawai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Input.add(txtID_Pegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 400, 30));

        txtID_Pembayaran.setBackground(new java.awt.Color(0, 255, 255));
        txtID_Pembayaran.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Input.add(txtID_Pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 400, 30));

        t29.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t29.setText("ID Pembayaran");
        Input.add(t29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        cmbPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPegawaiActionPerformed(evt);
            }
        });
        Input.add(cmbPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 400, 30));

        t30.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t30.setText("ID Pegawai");
        Input.add(t30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        t10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t10.setText("Tanggal Pemesanan");
        Input.add(t10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jdcTanggal_Pemesanan.setBackground(new java.awt.Color(0, 255, 255));
        jdcTanggal_Pemesanan.setDateFormatString("yyyy-MM-dd");
        Input.add(jdcTanggal_Pemesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 400, 30));

        Background.add(Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 20, 810, 700));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Background Pemesanan.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBayarActionPerformed
        // TODO add your handling code here:
        int bayar = Integer.parseInt(txtBayar.getText());
        int total_bayar = Integer.parseInt(txtTotal_Bayar.getText());
        int kembalian = bayar - total_bayar;
        txtKembalian.setText(String.valueOf(kembalian));
    }//GEN-LAST:event_txtBayarActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        pembayaran();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtID_PemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID_PemesananActionPerformed
        // TODO add your handling code here:
        select();
    }//GEN-LAST:event_txtID_PemesananActionPerformed

    private void cmbPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPegawaiActionPerformed
        // TODO add your handling code here:
        String nama_pegawai = (String) cmbPegawai.getSelectedItem();
        try {
            pst = conn.prepareStatement("SELECT * FROM pegawai WHERE nama_pegawai = ?");
            pst.setString(1, nama_pegawai);
            rs = pst.executeQuery();
            if (rs.next() == true) {
                String id_pegawai = rs.getString("id_pegawai");
                txtID_Pegawai.setText(id_pegawai.trim());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pesanan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbPegawaiActionPerformed

    public void setbackground(JButton p) {
        p.setBackground(new Color(255, 51, 255));
    }

    public void resetbackground(JButton pr) {
        pr.setBackground(new Color(255, 255, 255));
    }

    public void tampil_comboPegawai() throws SQLException {
        try {
            String query = "SELECT * FROM pegawai";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                cmbPegawai.addItem(rs.getString("nama_pegawai"));
            }
            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();
        } catch (SQLException ex) {
            Logger.getLogger(Koneksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void pembayaran() {

        try {
            String id_pembayaran = txtID_Pembayaran.getText();
            String id_pegawai = txtID_Pegawai.getText();
            String id_pemesanan = txtID_Pemesanan.getText();
            Date waktu = jdcTanggal_Pembayaran.getDate();
            int bayar = Integer.parseInt(txtBayar.getText());
            int kembalian = Integer.parseInt(txtKembalian.getText());
            String query = "INSERT INTO pembayaran(id_pembayaran, id_pegawai, waktu, bayar, kembalian, id_pemesanan)values(?,?,?,?,?,?)";
            pst = conn.prepareStatement(query);
            pst.setString(1, id_pembayaran);
            pst.setString(2, id_pegawai);
            pst.setString(3, ((JTextField) jdcTanggal_Pembayaran.getDateEditor().getUiComponent()).getText());
            pst.setInt(4, bayar);
            pst.setInt(5, kembalian);
            pst.setString(6, id_pemesanan);
            pst.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Pembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void select() {
        try {
            String query2 = "SELECT * FROM pemesanan WHERE id_pemesanan='" + txtID_Pemesanan.getText() + "'";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query2);
            if (rs.next()) {
                if (txtID_Pemesanan.getText().equalsIgnoreCase(rs.getString("id_pemesanan"))) {
                    String nama_pembeli = rs.getString("nama_pembeli");
                    Date tanggal_pegawai = rs.getDate("tanggal_pemesanan");
                    int total_bayar = rs.getInt("total_bayar");
                    txtNama_Pembeli.setText(nama_pembeli.trim());
                    jdcTanggal_Pemesanan.setDate(tanggal_pegawai);
                    txtTotal_Bayar.setText(String.valueOf(total_bayar).trim());

                } else {
                    JOptionPane.showMessageDialog(null, "ID Pemesanan tidak ada");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void autoNumber(JTextField f1) {
        String id_pembayaran = "M0";
        int i = 0;
        try {
//            conn = Connections.Koneksi.cekKoneksi();
            String sql = "SELECT * FROM pembayaran";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
//            ResultSet rs = conn.(id_pembayaran);

            while (rs.next()) {
                id_pembayaran = rs.getString("id_pembayaran");
            }
            id_pembayaran = id_pembayaran.substring(1);
            i = Integer.parseInt(id_pembayaran) + 1;
            id_pembayaran = "00" + i;
            id_pembayaran = "M0" + id_pembayaran.substring(id_pembayaran.length() - 2);
            f1.setText(id_pembayaran);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error pada ID Pembayaran");
            System.out.println(e.getMessage());
        }
    }

//    public void auto_numberPemesanan() {
//        try {
////            conn = Connections.Koneksi.cekKoneksi();
//            String sql = "SELECT * FROM detail_pemesanan";
//            st = conn.createStatement();
//            rs = st.executeQuery(sql);
//            if (rs.next()) {
//                String id = rs.getString("id_pemesanan").substring(1);
//                String an = "" + (id + 1);
//                String nol = "";
//
//                if (an.length() == 1) {
//                    nol = "00";
//                } else if (an.length() == 2) {
//                    nol = "0";
//                } else if (an.length() == 3) {
//                    nol = "";
//                }
//                txtID_Pemesanan.setText("P" + nol + an);
//            } else {
//                txtID_Pemesanan.setText("P0001");
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(Pesanan.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
//    public void pemesanan() {
//        try {
//            int lastinsertid = 0;
//            String id_pemesanan = txtID_Pemesanan.getText();
//            String nama_pembeli = txtNama_Pembeli.getText();
//            Date tanggal_pemesanan = jdcTanggal_Pembayaran.getDate();
//            int total_bayar = Integer.parseInt(txtTotal_Bayar.getText());
//            int bayar = Integer.parseInt(txtBayar.getText());
//            int kembalian = Integer.parseInt(txtKembalian.getText());
//            String query = "INSERT INTO pemesanan(id_pemesanan, nama_pembeli, tanggal_pemesanan, total_bayar, bayar, kembalian)values(?,?,?,?,?,?)";
//            pst = conn.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
//            pst.setString(1, id_pemesanan);
//            pst.setString(2, nama_pembeli);
//            pst.setString(3, ((JTextField) jdcTanggal_Pembayaran.getDateEditor().getUiComponent()).getText());
//            pst.setInt(4, total_bayar);
//            pst.setInt(5, bayar);
//            pst.setInt(6, kembalian);
//            pst.executeUpdate();
//            ResultSet generatekey = pst.getGeneratedKeys();
//            if (generatekey.next()) {
//                lastinsertid = generatekey.getInt(1);
//            }
//
//            int rows = tblPemesanan.getRowCount();
//            String query1 = "INSERT INTO detail_pemesanan (id_detail_pemesanan, id_pemesanan, id_menu, qty, sub_total) values(?,?,?,?,?)";
//            pst1 = conn.prepareStatement(query1);
//            String id_menu = "";
//            int qty = 0;
//            int sub_total = 0;
//            pst1.setInt(1, lastinsertid);
//            pst1.setString(2, id_pemesanan);
//            for (int i = 0; i < tblPemesanan.getRowCount(); i++) {
//                id_menu = (String) tblPemesanan.getValueAt(i, 0);
//                qty = Integer.parseInt((String) tblPemesanan.getValueAt(i, 3));
//                sub_total = Integer.parseInt((String) tblPemesanan.getValueAt(i, 4));
//                pst1.setString(3, id_menu);
//                pst1.setInt(4, qty);
//                pst1.setInt(5, sub_total);
//            }
//            pst1.executeUpdate();
//        } catch (SQLException ex) {
//            Logger.getLogger(Pembayaran.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Input;
    private javax.swing.JPanel Noodle;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbPegawai;
    private javax.swing.JPanel info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser jdcTanggal_Pembayaran;
    private com.toedter.calendar.JDateChooser jdcTanggal_Pemesanan;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t10;
    private javax.swing.JLabel t13;
    private javax.swing.JLabel t28;
    private javax.swing.JLabel t29;
    private javax.swing.JLabel t30;
    private javax.swing.JLabel t6;
    private javax.swing.JLabel t7;
    private javax.swing.JLabel t8;
    private javax.swing.JLabel t9;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtID_Pegawai;
    private javax.swing.JTextField txtID_Pembayaran;
    private javax.swing.JTextField txtID_Pemesanan;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtNama_Pembeli;
    private javax.swing.JTextField txtTotal_Bayar;
    // End of variables declaration//GEN-END:variables
}
