/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gacoan;

import java.awt.Color;
import java.util.Scanner;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Tharixs Akbar Ibnu A
 */
public class Pemesanan extends javax.swing.JFrame {

    /**
     * Creates new form Beranda
     */
    public Pemesanan() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Constructor = new javax.swing.JPanel();
        footer = new javax.swing.JPanel();
        btnSwip = new javax.swing.JButton();
        btnSwip2 = new javax.swing.JButton();
        btnSwip3 = new javax.swing.JButton();
        bckInfo = new javax.swing.JPanel();
        info = new javax.swing.JLabel();
        iknPemesanan = new javax.swing.JLabel();
        MAIN = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        BacgroundMenuMakanan2 = new javax.swing.JPanel();
        btnmenu1 = new javax.swing.JButton();
        btnmenu2 = new javax.swing.JButton();
        btnmenu3 = new javax.swing.JButton();
        TtlMakanan = new javax.swing.JLabel();
        BacgroundMenuMakanan = new javax.swing.JLabel();
        MenuMinuman = new javax.swing.JPanel();
        Logo1 = new javax.swing.JLabel();
        BacgroundMenuMakanan3 = new javax.swing.JPanel();
        btnmenu4 = new javax.swing.JButton();
        btnmenu5 = new javax.swing.JButton();
        btnmenu6 = new javax.swing.JButton();
        TtlMinuman = new javax.swing.JLabel();
        BacgroundMenuMakanan1 = new javax.swing.JLabel();
        MenuDimSum = new javax.swing.JPanel();
        Logo2 = new javax.swing.JLabel();
        BacgroundMenuMakanan4 = new javax.swing.JPanel();
        btnmenu7 = new javax.swing.JButton();
        btnmenu8 = new javax.swing.JButton();
        btnmenu9 = new javax.swing.JButton();
        TtlDimsum = new javax.swing.JLabel();
        BacgroundMenuMakanan5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Constructor.setLayout(null);

        footer.setBackground(new java.awt.Color(0, 179, 216,0));
        footer.setPreferredSize(new java.awt.Dimension(1680, 180));
        footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSwip.setBackground(new java.awt.Color(255, 51, 255 ,40));
        btnSwip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 255)));
        btnSwip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwipActionPerformed(evt);
            }
        });
        footer.add(btnSwip, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 62, 26, 28));

        btnSwip2.setBackground(new java.awt.Color(255, 255, 255 ,40));
        btnSwip2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 204), 1, true));
        btnSwip2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwip2ActionPerformed(evt);
            }
        });
        footer.add(btnSwip2, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 62, 26, 28));

        btnSwip3.setBackground(new java.awt.Color(255, 255, 255 ,40));
        btnSwip3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 204), 1, true));
        btnSwip3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwip3ActionPerformed(evt);
            }
        });
        footer.add(btnSwip3, new org.netbeans.lib.awtextra.AbsoluteConstraints(945, 62, 26, 28));

        bckInfo.setPreferredSize(new java.awt.Dimension(32, 32));
        bckInfo.setLayout(new java.awt.GridLayout(1, 0));

        info.setBackground(new java.awt.Color(255, 255, 255));
        info.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        info.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 255), 1, true));
        info.setIconTextGap(1);
        bckInfo.add(info);

        footer.add(bckInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 20, 20, 20));

        iknPemesanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pemesanan.png"))); // NOI18N
        footer.add(iknPemesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 30, -1, -1));

        Constructor.add(footer);
        footer.setBounds(0, 891, 1680, 160);

        MAIN.setMaximumSize(new java.awt.Dimension(1680, 1050));
        MAIN.setMinimumSize(new java.awt.Dimension(1680, 1050));
        MAIN.setPreferredSize(new java.awt.Dimension(1680, 1050));
        MAIN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoGacoan.png"))); // NOI18N
        MAIN.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 27, -1, -1));

        BacgroundMenuMakanan2.setBackground(new java.awt.Color(0, 179, 216,30));
        BacgroundMenuMakanan2.setMaximumSize(new java.awt.Dimension(1680, 1050));
        BacgroundMenuMakanan2.setMinimumSize(new java.awt.Dimension(1680, 1050));
        BacgroundMenuMakanan2.setPreferredSize(new java.awt.Dimension(1680, 1050));
        BacgroundMenuMakanan2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ii MIE SETAN.jpg"))); // NOI18N
        btnmenu1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 255), 1, true));
        btnmenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmenu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmenu1MouseExited(evt);
            }
        });
        btnmenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenu1ActionPerformed(evt);
            }
        });
        BacgroundMenuMakanan2.add(btnmenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 139, 357, 322));

        btnmenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ii MIE SETAN.jpg"))); // NOI18N
        btnmenu2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 255), 1, true));
        btnmenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmenu2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmenu2MouseExited(evt);
            }
        });
        btnmenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenu2ActionPerformed(evt);
            }
        });
        BacgroundMenuMakanan2.add(btnmenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 139, 357, 322));

        btnmenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ii MIE SETAN.jpg"))); // NOI18N
        btnmenu3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 255), 1, true));
        btnmenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmenu3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmenu3MouseExited(evt);
            }
        });
        btnmenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenu3ActionPerformed(evt);
            }
        });
        BacgroundMenuMakanan2.add(btnmenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 139, 357, 322));

        TtlMakanan.setFont(new java.awt.Font("Californian FB", 0, 60)); // NOI18N
        TtlMakanan.setForeground(new java.awt.Color(255, 51, 255));
        TtlMakanan.setText("Makanan");
        BacgroundMenuMakanan2.add(TtlMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 7, -1, -1));

        MAIN.add(BacgroundMenuMakanan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        BacgroundMenuMakanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Bacground.jpg"))); // NOI18N
        MAIN.add(BacgroundMenuMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -393, -1, 1681));

        Constructor.add(MAIN);
        MAIN.setBounds(0, 0, 1680, 1050);

        MenuMinuman.setMaximumSize(new java.awt.Dimension(1680, 1050));
        MenuMinuman.setMinimumSize(new java.awt.Dimension(1680, 1050));
        MenuMinuman.setPreferredSize(new java.awt.Dimension(1680, 1050));
        MenuMinuman.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo1.setIcon(new javax.swing.ImageIcon("D:\\KULIAH\\tugas kuliah\\Semester 2\\Workshop SI Berbasis Dekstop\\Desain\\Logo\\logoGacoan.png")); // NOI18N
        MenuMinuman.add(Logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 27, -1, -1));

        BacgroundMenuMakanan3.setBackground(new java.awt.Color(0, 179, 216,30));
        BacgroundMenuMakanan3.setMaximumSize(new java.awt.Dimension(1680, 1050));
        BacgroundMenuMakanan3.setMinimumSize(new java.awt.Dimension(1680, 1050));
        BacgroundMenuMakanan3.setPreferredSize(new java.awt.Dimension(1680, 1050));
        BacgroundMenuMakanan3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmenu4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tharixs Akbar Ibnu A\\Downloads\\ii MIE SETAN.jpg")); // NOI18N
        btnmenu4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 255), 1, true));
        btnmenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmenu4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmenu4MouseExited(evt);
            }
        });
        btnmenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenu4ActionPerformed(evt);
            }
        });
        BacgroundMenuMakanan3.add(btnmenu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 139, 357, 322));

        btnmenu5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tharixs Akbar Ibnu A\\Downloads\\ii MIE SETAN.jpg")); // NOI18N
        btnmenu5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 255), 1, true));
        btnmenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmenu5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmenu5MouseExited(evt);
            }
        });
        btnmenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenu5ActionPerformed(evt);
            }
        });
        BacgroundMenuMakanan3.add(btnmenu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 139, 357, 322));

        btnmenu6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tharixs Akbar Ibnu A\\Downloads\\ii MIE SETAN.jpg")); // NOI18N
        btnmenu6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 255), 1, true));
        btnmenu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmenu6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmenu6MouseExited(evt);
            }
        });
        btnmenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenu6ActionPerformed(evt);
            }
        });
        BacgroundMenuMakanan3.add(btnmenu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 139, 357, 322));

        TtlMinuman.setFont(new java.awt.Font("Californian FB", 0, 60)); // NOI18N
        TtlMinuman.setForeground(new java.awt.Color(255, 51, 255));
        TtlMinuman.setText("Minuman");
        BacgroundMenuMakanan3.add(TtlMinuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 7, -1, -1));

        MenuMinuman.add(BacgroundMenuMakanan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        BacgroundMenuMakanan1.setIcon(new javax.swing.ImageIcon("D:\\KULIAH\\tugas kuliah\\Semester 2\\Workshop SI Berbasis Dekstop\\Desain\\Bacground.jpg")); // NOI18N
        MenuMinuman.add(BacgroundMenuMakanan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -393, -1, 1681));

        Constructor.add(MenuMinuman);
        MenuMinuman.setBounds(0, 0, 1680, 1050);

        MenuDimSum.setMaximumSize(new java.awt.Dimension(1680, 1050));
        MenuDimSum.setMinimumSize(new java.awt.Dimension(1680, 1050));
        MenuDimSum.setPreferredSize(new java.awt.Dimension(1680, 1050));
        MenuDimSum.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo2.setIcon(new javax.swing.ImageIcon("D:\\KULIAH\\tugas kuliah\\Semester 2\\Workshop SI Berbasis Dekstop\\Desain\\Logo\\logoGacoan.png")); // NOI18N
        MenuDimSum.add(Logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 27, -1, -1));

        BacgroundMenuMakanan4.setBackground(new java.awt.Color(0, 179, 216,30));
        BacgroundMenuMakanan4.setMaximumSize(new java.awt.Dimension(1680, 1050));
        BacgroundMenuMakanan4.setMinimumSize(new java.awt.Dimension(1680, 1050));
        BacgroundMenuMakanan4.setPreferredSize(new java.awt.Dimension(1680, 1050));
        BacgroundMenuMakanan4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmenu7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tharixs Akbar Ibnu A\\Downloads\\ii MIE SETAN.jpg")); // NOI18N
        btnmenu7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 255), 1, true));
        btnmenu7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmenu7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmenu7MouseExited(evt);
            }
        });
        btnmenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenu7ActionPerformed(evt);
            }
        });
        BacgroundMenuMakanan4.add(btnmenu7, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 139, 357, 322));

        btnmenu8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tharixs Akbar Ibnu A\\Downloads\\ii MIE SETAN.jpg")); // NOI18N
        btnmenu8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 255), 1, true));
        btnmenu8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmenu8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmenu8MouseExited(evt);
            }
        });
        btnmenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenu8ActionPerformed(evt);
            }
        });
        BacgroundMenuMakanan4.add(btnmenu8, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 139, 357, 322));

        btnmenu9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tharixs Akbar Ibnu A\\Downloads\\ii MIE SETAN.jpg")); // NOI18N
        btnmenu9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 255), 1, true));
        btnmenu9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmenu9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmenu9MouseExited(evt);
            }
        });
        btnmenu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenu9ActionPerformed(evt);
            }
        });
        BacgroundMenuMakanan4.add(btnmenu9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 139, 357, 322));

        TtlDimsum.setFont(new java.awt.Font("Californian FB", 0, 60)); // NOI18N
        TtlDimsum.setForeground(new java.awt.Color(255, 51, 255));
        TtlDimsum.setText("Dim - Sum");
        BacgroundMenuMakanan4.add(TtlDimsum, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 7, -1, -1));

        MenuDimSum.add(BacgroundMenuMakanan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        BacgroundMenuMakanan5.setIcon(new javax.swing.ImageIcon("D:\\KULIAH\\tugas kuliah\\Semester 2\\Workshop SI Berbasis Dekstop\\Desain\\Bacground.jpg")); // NOI18N
        MenuDimSum.add(BacgroundMenuMakanan5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -393, -1, 1681));

        Constructor.add(MenuDimSum);
        MenuDimSum.setBounds(0, 0, 1680, 1050);

        getContentPane().add(Constructor);
        Constructor.setBounds(0, 0, 1680, 1050);

        setSize(new java.awt.Dimension(1702, 1106));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 String[] menu = {"mie iblis", "mie setan", "mie angel", "es teh", "es kopi", "es susu","somay","udang keju","udang rambutan"};
// String[] Menu = new String[menu.length];
    //    banyaknya menu
    int banyak[] = new int[9];
    
    private void btnmenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenu2ActionPerformed
        // TODO add your handling code here:
        tekan(menu[1]);
    }//GEN-LAST:event_btnmenu2ActionPerformed

    private void btnmenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenu3ActionPerformed
        // TODO add your handling code here:
        tekan(menu[2]);
    }//GEN-LAST:event_btnmenu3ActionPerformed

    private void btnSwipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwipActionPerformed
        // TODO add your handling code here:
        setbackground(btnSwip);
        resetbakcground(btnSwip2);
        resetbakcground(btnSwip3);

        MAIN.setVisible(true);
        MenuMinuman.setVisible(false);
        MenuDimSum.setVisible(true);
    }//GEN-LAST:event_btnSwipActionPerformed
    String judul1 = "Makanan";
    String judul2 = "Minuman";
    String judul3 = "DimSum";

    private void btnSwip2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwip2ActionPerformed
        // TODO add your handling code here:

        setbackground(btnSwip2);
        resetbakcground(btnSwip);
        resetbakcground(btnSwip3);

//        TtlMakanan.setText(judul2);
        MAIN.setVisible(false);
        MenuMinuman.setVisible(true);
        MenuDimSum.setVisible(true);

    }//GEN-LAST:event_btnSwip2ActionPerformed

    private void btnSwip3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwip3ActionPerformed
        // TODO add your handling code here:
        setbackground(btnSwip3);
        resetbakcground(btnSwip);
        resetbakcground(btnSwip2);

//        halaman minuman

        MAIN.setVisible(false);
        MenuMinuman.setVisible(false);
        MenuDimSum.setVisible(true);

    }//GEN-LAST:event_btnSwip3ActionPerformed

    private void btnmenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenu1ActionPerformed
        tekan(menu[0]);
    }//GEN-LAST:event_btnmenu1ActionPerformed
    String alamat = "/img/ii MIE SETAN.jpg";
    String alamat2 = "/img/ii MIE SETAN2.jpg";
    private void btnmenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenu1MouseExited
        // TODO add your handling code here:
        btnmenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource(alamat)));
    }//GEN-LAST:event_btnmenu1MouseExited

    private void btnmenu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenu1MouseEntered
        // TODO add your handling code here:\
        btnmenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource(alamat2)));
    }//GEN-LAST:event_btnmenu1MouseEntered

    private void btnmenu2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenu2MouseEntered
        // TODO add your handling code here:
        btnmenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource(alamat2)));
    }//GEN-LAST:event_btnmenu2MouseEntered

    private void btnmenu2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenu2MouseExited
        // TODO add your handling code here:
        btnmenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource(alamat)));
    }//GEN-LAST:event_btnmenu2MouseExited

    private void btnmenu3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenu3MouseEntered
        // TODO add your handling code here:
        btnmenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource(alamat2)));
    }//GEN-LAST:event_btnmenu3MouseEntered

    private void btnmenu3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenu3MouseExited
        // TODO add your handling code here:
        btnmenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource(alamat)));
    }//GEN-LAST:event_btnmenu3MouseExited

    private void btnmenu4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenu4MouseEntered
        // TODO add your handling code here:
        btnmenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource(alamat2)));
    }//GEN-LAST:event_btnmenu4MouseEntered

    private void btnmenu4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenu4MouseExited
        // TODO add your handling code here:
        btnmenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource(alamat)));
    }//GEN-LAST:event_btnmenu4MouseExited

    private void btnmenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenu4ActionPerformed
        // TODO add your handling code here:
        tekan(menu[3]);
    }//GEN-LAST:event_btnmenu4ActionPerformed

    private void btnmenu5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenu5MouseEntered
        // TODO add your handling code here:
        btnmenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource(alamat2)));
    }//GEN-LAST:event_btnmenu5MouseEntered

    private void btnmenu5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenu5MouseExited
        // TODO add your handling code here:
        btnmenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource(alamat)));
    }//GEN-LAST:event_btnmenu5MouseExited

    private void btnmenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenu5ActionPerformed
        // TODO add your handling code here:
        tekan(menu[4]);
    }//GEN-LAST:event_btnmenu5ActionPerformed

    private void btnmenu6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenu6MouseEntered
        // TODO add your handling code here:
        btnmenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource(alamat2)));
    }//GEN-LAST:event_btnmenu6MouseEntered

    private void btnmenu6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenu6MouseExited
        // TODO add your handling code here:
        btnmenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource(alamat)));
    }//GEN-LAST:event_btnmenu6MouseExited

    private void btnmenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenu6ActionPerformed
        // TODO add your handling code here:
        tekan(menu[5]);
    }//GEN-LAST:event_btnmenu6ActionPerformed

    private void btnmenu7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenu7MouseEntered
        // TODO add your handling code here:
        btnmenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource(alamat2)));
    }//GEN-LAST:event_btnmenu7MouseEntered

    private void btnmenu7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenu7MouseExited
        // TODO add your handling code here:
        btnmenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource(alamat)));
    }//GEN-LAST:event_btnmenu7MouseExited

    private void btnmenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenu7ActionPerformed
        // TODO add your handling code here:
        tekan(menu[6]);
    }//GEN-LAST:event_btnmenu7ActionPerformed

    private void btnmenu8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenu8MouseEntered
        // TODO add your handling code here:
        btnmenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource(alamat2)));
    }//GEN-LAST:event_btnmenu8MouseEntered

    private void btnmenu8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenu8MouseExited
        // TODO add your handling code here:
        btnmenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource(alamat)));
    }//GEN-LAST:event_btnmenu8MouseExited

    private void btnmenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenu8ActionPerformed
        // TODO add your handling code here:
        tekan(menu[7]);
    }//GEN-LAST:event_btnmenu8ActionPerformed

    private void btnmenu9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenu9MouseEntered
        // TODO add your handling code here:
        btnmenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource(alamat2)));
    }//GEN-LAST:event_btnmenu9MouseEntered

    private void btnmenu9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenu9MouseExited
        // TODO add your handling code here:
        btnmenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource(alamat)));
    }//GEN-LAST:event_btnmenu9MouseExited

    private void btnmenu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenu9ActionPerformed
        // TODO add your handling code here:
        tekan(menu[8]);
    }//GEN-LAST:event_btnmenu9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BacgroundMenuMakanan;
    private javax.swing.JLabel BacgroundMenuMakanan1;
    private javax.swing.JPanel BacgroundMenuMakanan2;
    private javax.swing.JPanel BacgroundMenuMakanan3;
    private javax.swing.JPanel BacgroundMenuMakanan4;
    private javax.swing.JLabel BacgroundMenuMakanan5;
    private javax.swing.JPanel Constructor;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel Logo2;
    private javax.swing.JPanel MAIN;
    private javax.swing.JPanel MenuDimSum;
    private javax.swing.JPanel MenuMinuman;
    private javax.swing.JLabel TtlDimsum;
    private javax.swing.JLabel TtlMakanan;
    private javax.swing.JLabel TtlMinuman;
    private javax.swing.JPanel bckInfo;
    private javax.swing.JButton btnSwip;
    private javax.swing.JButton btnSwip2;
    private javax.swing.JButton btnSwip3;
    private javax.swing.JButton btnmenu1;
    private javax.swing.JButton btnmenu2;
    private javax.swing.JButton btnmenu3;
    private javax.swing.JButton btnmenu4;
    private javax.swing.JButton btnmenu5;
    private javax.swing.JButton btnmenu6;
    private javax.swing.JButton btnmenu7;
    private javax.swing.JButton btnmenu8;
    private javax.swing.JButton btnmenu9;
    private javax.swing.JPanel footer;
    private javax.swing.JLabel iknPemesanan;
    private javax.swing.JLabel info;
    // End of variables declaration//GEN-END:variables

    public void setbackground(JButton p) {
        p.setBackground(new Color(255, 51, 255));
    }

    public void resetbakcground(JButton pr) {
        pr.setBackground(new Color(255, 255, 255));
    }

    int Info;

    public void tekan(String menu) {

        Info += 1;
        info.setText(String.valueOf(" " + Info));
        bckInfo.setBackground(new Color(255, 51, 255));
        info.setForeground(Color.WHITE);
        if (Info >= 10) {
            info.setFont(new java.awt.Font("Segoe UI", 0, 12));
        }

        if (menu == "mie iblis") {
            banyak[0] += 1;
            System.out.println(menu);
        } else if (menu == "mie setan") {
            banyak[1] += 1;
            System.out.println(menu);
        } else if (menu == "mie angel") {
            banyak[2] += 1;
            System.out.println(menu);
        } else if (menu == "es teh") {
            banyak[3] += 1;
            System.out.println(menu);
        } else if (menu == "es kopi") {
            banyak[4] += 1;
            System.out.println(menu);
        } else if (menu == "es susu") {
            banyak[5] += 1;
            System.out.println(menu);
        } else if (menu == "somay") {
            banyak[6] += 1;
            System.out.println(menu);
        } else if (menu == "udang keju") {
            banyak[7] += 1;
            System.out.println(menu);
        } else if (menu == "udang rambutan") {
            banyak[8] += 1;
            System.out.println(menu);
        }

        total();
        System.out.println("total pesanan anda " + Info);
    }

    public void total() {
        System.out.println("===== pesanan anda =====");
        System.out.println(banyak[0] + " " + menu[0]);
        System.out.println(banyak[1] + " " + menu[1]);
        System.out.println(banyak[2] + " " + menu[2]);
        System.out.println(banyak[3] + " " + menu[3]);
        System.out.println(banyak[4] + " " + menu[4]);
        System.out.println(banyak[5] + " " + menu[5]);
        System.out.println(banyak[6] + " " + menu[6]);
        System.out.println(banyak[7] + " " + menu[7]);
        System.out.println(banyak[8] + " " + menu[8]);
    }
}
